srv=net.createServer(net.TCP) 
srv:listen(80,function(conn) 
    conn:on("receive",function(conn,payload) 
    conn:send('HTTP/1.1 200 OK\n\n')
    conn:send('<!DOCTYPE HTML>\n')
    conn:send('<html>\n')
    conn:send('<head><meta  content="text/html; charset=utf-8">\n')
    conn:send('<title>ESP8266</title></head>\n')
    conn:send('<body>\n')
    conn:send("<h1> ESP8266<BR>Server is working!</h1>")
    conn:send('</body></html>\n')
    conn:on("sent",function(conn) conn:close()  end)
	end) 
end)
          
